package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChoiceQuestion generated by hbm2java
 */
@Entity
@Table(name = "CHOICE_QUESTION", schema = "dbo", catalog = "EXAM")
public class ChoiceQuestion implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;

	@Column(name = "descript")
	private String descript;

	@Column(name = "Answer", length = 1)
	private Character answer;

	@Column(name = "A", length = 100)
	private String a;

	@Column(name = "B", length = 100)
	private String b;

	@Column(name = "C", length = 100)
	private String c;

	@Column(name = "D", length = 100)
	private String d;

	@Column(name = "degree", length = 2)
	private String degree;

	@Column(name = "Knowlegepoint", length = 10)
	private String knowlegePoint;

	@Column(name = "CourseID", length = 20)
	private String courseId;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "choiceQuestion")
	private Set<ErrorSet> errorSets = new HashSet<ErrorSet>(0);

	public ChoiceQuestion() {
	}

	public ChoiceQuestion(int id) {
		this.id = id;
	}

	public ChoiceQuestion(int id, String descript, Character answer, String a, String b, String c, String d,
			String degree, String knowlegePoint, String courseId, Set<ErrorSet> errorSets) {
		this.id = id;
		this.descript = descript;
		this.answer = answer;
		this.a = a;
		this.b = b;
		this.c = c;
		this.d = d;
		this.degree = degree;
		this.knowlegePoint = knowlegePoint;
		this.courseId = courseId;
		this.errorSets = errorSets;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	public Character getAnswer() {
		return this.answer;
	}

	public void setAnswer(Character answer) {
		this.answer = answer;
	}

	public String getA() {
		return this.a;
	}

	public void setA(String a) {
		this.a = a;
	}

	public String getB() {
		return this.b;
	}

	public void setB(String b) {
		this.b = b;
	}

	public String getC() {
		return this.c;
	}

	public void setC(String c) {
		this.c = c;
	}

	public String getD() {
		return this.d;
	}

	public void setD(String d) {
		this.d = d;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getKnowlegePoint() {
		return this.knowlegePoint;
	}

	public void setKnowlegePoint(String knowlegePoint) {
		this.knowlegePoint = knowlegePoint;
	}

	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public Set<ErrorSet> getErrorSets() {
		return this.errorSets;
	}

	public void setErrorSets(Set<ErrorSet> errorSets) {
		this.errorSets = errorSets;
	}

}
