package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ComprehensiveQuestion generated by hbm2java
 */
@Entity
@Table(name = "COMPREHENSIVE_QUESTION", schema = "dbo", catalog = "EXAM")
public class ComprehensiveQuestion implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;

	@Column(name = "Descript")
	private String descript;

	@Column(name = "Answer")
	private String answer;

	@Column(name = "images", length = 10)
	private String images;

	@Column(name = "degree", length = 2)
	private String degree;

	@Column(name = "Knowlegepoint", length = 10)
	private String knowlegePoint;

	@Column(name = "CourseID", length = 20)
	private String courseId;

	public ComprehensiveQuestion() {
	}

	public ComprehensiveQuestion(int id) {
		this.id = id;
	}

	public ComprehensiveQuestion(int id, String descript, String answer, String images, String degree,
			String knowlegePoint, String courseId) {
		this.id = id;
		this.descript = descript;
		this.answer = answer;
		this.images = images;
		this.degree = degree;
		this.knowlegePoint = knowlegePoint;
		this.courseId = courseId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getKnowlegePoint() {
		return this.knowlegePoint;
	}

	public void setKnowlegePoint(String knowlegePoint) {
		this.knowlegePoint = knowlegePoint;
	}

	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

}
