package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ErrorSet generated by hbm2java
 */
@Entity
@Table(name = "ERROR_SET", schema = "dbo", catalog = "EXAM")
public class ErrorSet implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHOICE_QUESTIONID")
	private ChoiceQuestion choiceQuestion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentID")
	private Student student;

	public ErrorSet() {
	}

	public ErrorSet(int id) {
		this.id = id;
	}

	public ErrorSet(int id, ChoiceQuestion choiceQuestion, Student student) {
		this.id = id;
		this.choiceQuestion = choiceQuestion;
		this.student = student;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public ChoiceQuestion getChoiceQuestion() {
		return this.choiceQuestion;
	}

	public void setChoiceQuestion(ChoiceQuestion choiceQuestion) {
		this.choiceQuestion = choiceQuestion;
	}


	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
