package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExamScores generated by hbm2java
 */
@Entity
@Table(name = "EXAM_SCORES", schema = "dbo", catalog = "EXAM")
public class ExamScores implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paperID")
	private Exam exam;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentID")
	private Student student;
	
	@Column(name = "choice_question_answerset", length = 200)
	private String choiceQuestionAnswerset;
	
	@Column(name = "shortanswer_question_answerset", length = 500)
	private String shortanswerQuestionAnswerset;
	
	@Column(name = "comprehensive_question_answerset")
	private Serializable comprehensiveQuestionAnswerset;
	
	@Column(name = "choice_question_score", length = 200)
	private String choiceQuestionScore;
	
	@Column(name = "shortanswer_question_score",length = 100)
	private String shortanswerQuestionScore;
	
	@Column(name = "compreehensive_score",length = 100)
	private String compreehensiveScore;
	
	@Column(name = "score")
	private Byte score;
	
	@Column(name = "time_cost")
	private Byte timeCost;
	
	@Column(name = "marked")
	private Boolean marked;

	public ExamScores() {
	}

	public ExamScores(int id) {
		this.id = id;
	}

	public ExamScores(int id, Exam exam, Student student, String choiceQuestionAnswerset,
			String shortanswerQuestionAnswerset, Serializable comprehensiveQuestionAnswerset, String choiceQuestionScore,
			String shortanswerQuestionScore, String compreehensiveScore, Byte score, Byte timeCost, Boolean marked) {
		this.id = id;
		this.exam = exam;
		this.student = student;
		this.choiceQuestionAnswerset = choiceQuestionAnswerset;
		this.shortanswerQuestionAnswerset = shortanswerQuestionAnswerset;
		this.comprehensiveQuestionAnswerset = comprehensiveQuestionAnswerset;
		this.choiceQuestionScore = choiceQuestionScore;
		this.shortanswerQuestionScore = shortanswerQuestionScore;
		this.compreehensiveScore = compreehensiveScore;
		this.score = score;
		this.timeCost = timeCost;
		this.marked = marked;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public Exam getExam() {
		return this.exam;
	}

	public void setExam(Exam exam) {
		this.exam = exam;
	}


	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public String getChoiceQuestionAnswerset() {
		return this.choiceQuestionAnswerset;
	}

	public void setChoiceQuestionAnswerset(String choiceQuestionAnswerset) {
		this.choiceQuestionAnswerset = choiceQuestionAnswerset;
	}

	public String getShortanswerQuestionAnswerset() {
		return this.shortanswerQuestionAnswerset;
	}

	public void setShortanswerQuestionAnswerset(String shortanswerQuestionAnswerset) {
		this.shortanswerQuestionAnswerset = shortanswerQuestionAnswerset;
	}

	public Serializable getComprehensiveQuestionAnswerset() {
		return this.comprehensiveQuestionAnswerset;
	}

	public void setComprehensiveQuestionAnswerset(Serializable comprehensiveQuestionAnswerset) {
		this.comprehensiveQuestionAnswerset = comprehensiveQuestionAnswerset;
	}

	public String getChoiceQuestionScore() {
		return this.choiceQuestionScore;
	}

	public void setChoiceQuestionScore(String choiceQuestionScore) {
		this.choiceQuestionScore = choiceQuestionScore;
	}

	public String getShortanswerQuestionScore() {
		return this.shortanswerQuestionScore;
	}

	public void setShortanswerQuestionScore(String shortanswerQuestionScore) {
		this.shortanswerQuestionScore = shortanswerQuestionScore;
	}

	public String getCompreehensiveScore() {
		return this.compreehensiveScore;
	}

	public void setCompreehensiveScore(String compreehensiveScore) {
		this.compreehensiveScore = compreehensiveScore;
	}

	public Byte getScore() {
		return this.score;
	}

	public void setScore(Byte score) {
		this.score = score;
	}

	public Byte getTimeCost() {
		return this.timeCost;
	}

	public void setTimeCost(Byte timeCost) {
		this.timeCost = timeCost;
	}

	
	public Boolean getMarked() {
		return this.marked;
	}

	public void setMarked(Boolean marked) {
		this.marked = marked;
	}

}
