package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Exam generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler","fieldHandler"}) 
@Table(name = "EXAM", schema = "dbo", catalog = "EXAM")
public class Exam implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "paperID", unique = true, nullable = false)
	private int paperId;
	
	@Column(name = "courseID", length = 20)
	private String courseId;
	
	@JsonIgnore
	@Column(name = "choice_question_set", length = 200)
	private String choiceQuestionSet;
	
	@JsonIgnore
	@Column(name="choice_question_score")
	private Integer CQScore;
	
	@JsonIgnore
	@Column(name = "shortanswer_question_set", length = 100)
	private String shortanswerQuestionSet;
	
	@JsonIgnore
	@Column(name="shortanswer_question_score")
	private Integer SQScore;
	
	@JsonIgnore
	@Column(name = "comprehensive_question_set", length = 100)
	private String comprehensiveQuestionSet;
	
	@JsonIgnore
	@Column(name="comprehensive_question_score")
	private Integer CphQScore;
	
	@Column(name = "begin_time", length = 20)
	private String beginTime;
	
	@Column(name = "end_time", length = 20)
	private String endTime;
	
	public String getBeginTime() {
		return beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exam")
	private Set<ExamScores> examScoreses = new HashSet<ExamScores>(0);

	public Exam() {
	}

	public Exam(int paperId) {
		this.paperId = paperId;
	}

	public Exam(int paperId, String courseId, String choiceQuestionSet, String shortanswerQuestionSet,
			String comprehensiveQuestionSet, String beginTime,String endTime, Set<ExamScores> examScoreses) {
		this.paperId = paperId;
		this.courseId = courseId;
		this.choiceQuestionSet = choiceQuestionSet;
		this.shortanswerQuestionSet = shortanswerQuestionSet;
		this.comprehensiveQuestionSet = comprehensiveQuestionSet;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.examScoreses = examScoreses;
	}


	public Integer getCQScore() {
		return CQScore;
	}

	public void setCQScore(Integer cQScore) {
		CQScore = cQScore;
	}

	public Integer getSQScore() {
		return SQScore;
	}

	public void setSQScore(Integer sQScore) {
		SQScore = sQScore;
	}

	public Integer getCphQScore() {
		return CphQScore;
	}

	public void setCphQScore(Integer cphQScore) {
		CphQScore = cphQScore;
	}

	public int getPaperId() {
		return this.paperId;
	}

	public void setPaperId(int paperId) {
		this.paperId = paperId;
	}

	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public String getChoiceQuestionSet() {
		return this.choiceQuestionSet;
	}

	public void setChoiceQuestionSet(String choiceQuestionSet) {
		this.choiceQuestionSet = choiceQuestionSet;
	}

	public String getShortanswerQuestionSet() {
		return this.shortanswerQuestionSet;
	}

	public void setShortanswerQuestionSet(String shortanswerQuestionSet) {
		this.shortanswerQuestionSet = shortanswerQuestionSet;
	}

	public String getComprehensiveQuestionSet() {
		return this.comprehensiveQuestionSet;
	}

	public void setComprehensiveQuestionSet(String comprehensiveQuestionSet) {
		this.comprehensiveQuestionSet = comprehensiveQuestionSet;
	}


	
	public Set<ExamScores> getExamScoreses() {
		return this.examScoreses;
	}

	public void setExamScoreses(Set<ExamScores> examScoreses) {
		this.examScoreses = examScoreses;
	}

}
