package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * SelfCheckHistory generated by hbm2java
 */
@Entity
@Table(name = "SELF_CHECK_HISTORY", schema = "dbo", catalog = "EXAM")
public class SelfCheckHistory implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentID")
	private Student student;
	
	@Column(name = "courseID", length = 20)
	private String courseId;
	
	@Column(name = "Score")
	private Integer score;
	
	@Column(name = "time", length = 14)
	private String time;

	public SelfCheckHistory() {
	}

	public SelfCheckHistory(int id) {
		this.id = id;
	}

	public SelfCheckHistory(int id, Student student, String courseId, Integer score, String time) {
		this.id = id;
		this.student = student;
		this.courseId = courseId;
		this.score = score;
		this.time = time;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}


	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

}
