package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShortanswerQuestion generated by hbm2java
 */
@Entity
@Table(name = "SHORTANSWER_QUESTION", schema = "dbo", catalog = "EXAM")
public class ShortanswerQuestion implements java.io.Serializable {

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	
	@Column(name = "Descript")
	private Serializable descript;
	
	@Column(name = "Answer", length = 50)
	private String answer;
	
	@Column(name = "degree", length = 2)
	private String degree;
	
	@Column(name = "Knowlegepoint", length = 10)
	private String knowlegePoint;
	
	@Column(name = "Courseid", length = 20)
	private String courseId;

	public ShortanswerQuestion() {
	}

	public ShortanswerQuestion(int id) {
		this.id = id;
	}

	public ShortanswerQuestion(int id, Serializable descript, String answer, String degree, String knowlegePoint,
			String courseId) {
		this.id = id;
		this.descript = descript;
		this.answer = answer;
		this.degree = degree;
		this.knowlegePoint = knowlegePoint;
		this.courseId = courseId;
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	public Serializable getDescript() {
		return this.descript;
	}

	public void setDescript(Serializable descript) {
		this.descript = descript;
	}


	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	
	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	
	public String getKnowlegePoint() {
		return this.knowlegePoint;
	}

	public void setKnowlegePoint(String knowlegePoint) {
		this.knowlegePoint = knowlegePoint;
	}

	
	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

}
