package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StudentCourseId generated by hbm2java
 */
@Embeddable
public class StudentCourseId implements java.io.Serializable {

	private String courseId;
	private int studentId;
	
	public StudentCourseId() {
	}

	public StudentCourseId(String courseId, int studentId) {
		this.courseId = courseId;
		this.studentId = studentId;
	}

	@Column(name = "courseID", nullable = false, length = 20)
	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@Column(name = "studentID", nullable = false)
	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentCourseId))
			return false;
		StudentCourseId castOther = (StudentCourseId) other;

		return ((this.getCourseId() == castOther.getCourseId()) || (this.getCourseId() != null
				&& castOther.getCourseId() != null && this.getCourseId().equals(castOther.getCourseId())))
				&& (this.getStudentId() == castOther.getStudentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCourseId() == null ? 0 : this.getCourseId().hashCode());
		result = 37 * result + this.getStudentId();
		return result;
	}

}
