 package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


/**
 * Student generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler","fieldHandler"}) 
@Table(name = "STUDENT", schema = "dbo", catalog = "EXAM")
public class Student implements java.io.Serializable {

	@Id
	@Column(name = "studentID", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int studentId;

	@Column(name = "name", length = 10)
	private String name;

	@Column(name = "password", length = 10)
	private String password;

	@Column(name = "mailbox", length = 25)
	private String mailbox;

	@Column(name = "phone", length = 20)
	private String phone;

	@Column(name = "identitycard", length = 18)
	private String identityCard;

	@Column(name = "safequestion", length = 50)
	private String safeQuestion;

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	private Set<StudentCourse> studentCourses = new HashSet<StudentCourse>(0);

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	private Set<ErrorSet> errorSets = new HashSet<ErrorSet>(0);

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	private Set<ExamScores> examScoreses = new HashSet<ExamScores>(0);

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	private Set<SelfCheckHistory> selfCheckHistories = new HashSet<SelfCheckHistory>(0);

	public Student() {
	}

	public Student(int studentId) {
		this.studentId = studentId;
	}

	public Student(int studentId, String name, String password, String mailbox, String phone, String identityCard,
			String safeQuestion, Set<StudentCourse> studentCourses, Set<ErrorSet> errorSets,
			Set<ExamScores> examScoreses, Set<SelfCheckHistory> selfCheckHistories) {
		this.studentId = studentId;
		this.name = name;
		this.password = password;
		this.mailbox = mailbox;
		this.phone = phone;
		this.identityCard = identityCard;
		this.safeQuestion = safeQuestion;
		this.studentCourses = studentCourses;
		this.errorSets = errorSets;
		this.examScoreses = examScoreses;
		this.selfCheckHistories = selfCheckHistories;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMailbox() {
		return this.mailbox;
	}

	public void setMailbox(String mailbox) {
		this.mailbox = mailbox;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getIdentityCard() {
		return this.identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

	public String getSafeQuestion() {
		return this.safeQuestion;
	}

	public void setSafeQuestion(String safeQuestion) {
		this.safeQuestion = safeQuestion;
	}

	public Set<StudentCourse> getStudentCourses() {
		return this.studentCourses;
	}

	public void setStudentCourses(Set<StudentCourse> studentCourses) {
		this.studentCourses = studentCourses;
	}

	public Set<ErrorSet> getErrorSets() {
		return this.errorSets;
	}

	public void setErrorSets(Set<ErrorSet> errorSets) {
		this.errorSets = errorSets;
	}

	public Set<ExamScores> getExamScoreses() {
		return this.examScoreses;
	}

	public void setExamScoreses(Set<ExamScores> examScoreses) {
		this.examScoreses = examScoreses;
	}

	public Set<SelfCheckHistory> getSelfCheckHistories() {
		return this.selfCheckHistories;
	}

	public void setSelfCheckHistories(Set<SelfCheckHistory> selfCheckHistories) {
		this.selfCheckHistories = selfCheckHistories;
	}

}
