package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "TEACHER", schema = "dbo", catalog = "EXAM")
public class Teacher implements java.io.Serializable {

	@Id
	@Column(name = "teacherID", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int teacherId;

	@Column(name = "name", length = 10)
	private String name;

	@Column(name = "password", length = 10)
	private String password;

	@Column(name = "mailbox", length = 25)
	private String mailbox;

	@Column(name = "phone", length = 20)
	private String phone;

	@Column(name = "identitycard", length = 18)
	private String identityCard;

	@Column(name = "safequestion", length = 50)
	private String safeQuestion;

	@Column(name = "role", length = 7)
	private String role;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	private Set<TeacherCourse> teacherCourses = new HashSet<TeacherCourse>(0);

	public Teacher() {
	}

	public Teacher(int teacherId) {
		this.teacherId = teacherId;
	}

	public Teacher(int teacherId, String name, String password, String mailbox, String phone, String identityCard,
			String safeQuestion, String role, Set<TeacherCourse> teacherCourses) {
		this.teacherId = teacherId;
		this.name = name;
		this.password = password;
		this.mailbox = mailbox;
		this.phone = phone;
		this.identityCard = identityCard;
		this.safeQuestion = safeQuestion;
		this.role = role;
		this.teacherCourses = teacherCourses;
	}
	

	public int getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMailbox() {
		return this.mailbox;
	}

	public void setMailbox(String mailbox) {
		this.mailbox = mailbox;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getIdentityCard() {
		return this.identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

	public String getSafeQuestion() {
		return this.safeQuestion;
	}

	public void setSafeQuestion(String safeQuestion) {
		this.safeQuestion = safeQuestion;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set<TeacherCourse> getTeacherCourses() {
		return this.teacherCourses;
	}

	public void setTeacherCourses(Set<TeacherCourse> teacherCourses) {
		this.teacherCourses = teacherCourses;
	}

}
