package com.entity;
// Generated 2017-10-11 16:06:00 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TeacherCourse generated by hbm2java
 */
@Entity
@Table(name = "TEACHER_COURSE", schema = "dbo", catalog = "EXAM")
public class TeacherCourse implements java.io.Serializable {

	private TeacherCourseId id;
	private Teacher teacher;

	public TeacherCourse() {
	}

	public TeacherCourse(TeacherCourseId id, Teacher teacher) {
		this.id = id;
		this.teacher = teacher;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "courseId", column = @Column(name = "courseID", nullable = false, length = 20)),
			@AttributeOverride(name = "teacherId", column = @Column(name = "teacherID", nullable = false)) })
	public TeacherCourseId getId() {
		return this.id;
	}

	public void setId(TeacherCourseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "teacherID", nullable = false, insertable = false, updatable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

}
